### ISSUE TITLE
Version 1.0.1 blows up with python 2

### ISSUE THREAD

**Issue by foobacca** [reverbc/pylint-pytest#11]
From our pipeline:

```
pylint --output-format=parseable --reports=n local/cindexd local/tests dev libcindexd/libcindexd libcindexd/libcindexd_tests
Using config file /var/lib/jenkins/workspace/ODS_cindexd_cindexd_main/pylintrc
Traceback (most recent call last):
  File "/tmp/cindexd-venvs/core/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/tmp/cindexd-venvs/core/lib/python2.7/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/tmp/cindexd-venvs/core/lib/python2.7/site-packages/pylint/lint.py", line 1353, in __init__
    linter.check(args)
  File "/tmp/cindexd-venvs/core/lib/python2.7/site-packages/pylint/lint.py", line 774, in check
    self._do_check(files_or_modules)
  File "/tmp/cindexd-venvs/core/lib/python2.7/site-packages/pylint/lint.py", line 907, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/tmp/cindexd-venvs/core/lib/python2.7/site-packages/pylint/lint.py", line 986, in check_astroid_module
    walker.walk(ast_node)
  File "/tmp/cindexd-venvs/core/lib/python2.7/site-packages/pylint/utils.py", line 1011, in walk
    cb(astroid)
  File "/tmp/cindexd-venvs/core/lib/python2.7/site-packages/pylint_pytest/checkers/fixture.py", line 76, in visit_module
    sys_path = sys.path.copy()
AttributeError: 'list' object has no attribute 'copy'
```

The `copy()` appears to have been introduced in https://github.com/reverbc/pylint-pytest/commit/6c11a57c9dec681b952fa07d4b282b2c82d5ac17

If you don't support python2 any more, then it would be good to ensure that pip won't install the new version.  [This guide](https://packaging.python.org/guides/dropping-older-python-versions/) suggests using `Requires-Python:` in your `setup.py`

**Comment by reverbc** [comment]
Thanks for reporting the issue. I fixed it in 1.0.2 and yanked 1.0.0 and 1.0.1 from pypi so they shouldn't be picked up by `pip` automatically anymore.
